name = "Tutelage"
license = "MIT"
licenselink = "https://github.com/naclomi/tutelage/blob/main/LICENSE"
description = "Single-page tutorial theme"
homepage = "https://github.com/naclomi/tutelage"
tags = []
features = []
min_version = "0.115.2"

[author]
  name = "Naomi Alterman"
  homepage = "https://www.nlalterman.com"
